# Generated by Django 5.1.4 on 2024-12-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.CharField(
                blank=True,
                help_text="Введите ID Вашего профиля Telegram",
                max_length=255,
                null=True,
                verbose_name="ID профиля Telegram",
            ),
        ),
    ]
